[project]
name = "starwars-func-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "functions-framework>=3.10.0",
]

[dependency-groups]
dev = [
    "pyright>=1.1.408",
]
